debug: false
check_updates: true
gui_menus:
  
  vote_menu:
    file: vote_menu.yml

  rank_menu:
    file: ranks.yml

  rtp_menu:
    file: rtp_menu.yml

  warp_menu:
    file: dungeons_warp.yml
